[package]
name = "eaimty_bot"
description = "个人用 Telegram Bot"
version = "0.6.1"
authors = ["EAimTY <ea.imty@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "GPL-3.0 License"
repository = "https://github.com/EAimTY/eaimty_bot"

[dependencies]
carapax = { version = "0.10", default-features = false, features = ["session-fs"] }
getopts = { version = "0.2", default-features = false }
reqwest = { version = "0.11", default-features = false }
serde = { version = "1.0", default-features = false }
tempfile = { version = "3.2", default-features = false }
leptess = { version = "0.13", default-features = false }
tokio = { version = "1.8", default-features = false, features = ["rt-multi-thread", "macros"] }
tokio-stream = { version = "0.1", default-features = false }

[profile.release]
lto = true
codegen-units = 1
