on:
  workflow_dispatch:

name: release

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install -y upx libtesseract-dev libleptonica-dev

      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - run: cargo build --release
      - run: mv target/release/eaimty_bot eaimty_bot-linux-amd64

      - run: upx --best eaimty_bot-linux-amd64

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "eaimty_bot-linux-amd64"
          tag: "latest"
          name: "latest"
          body: "latest release"
          allowUpdates: true
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
