name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install binutils upx tesseract-ocr libtesseract-dev libleptonica-dev

      - uses: actions/checkout@v2
      - run: git fetch --all --tags

      - name: Version check
        id: version_check
        uses: thebongy/version-check@v1
        with:
          file: Cargo.toml
          tagFormat: v${version}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Binary Optimization
        run: |
          strip -s target/release/eaimty_bot
          upx -9 target/release/eaimty_bot

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version_check.outputs.releaseVersion }}
          artifacts: "target/release/eaimty_bot"
          token: ${{ secrets.GITHUB_TOKEN }}
